apiVersion: v1
kind: Pod
metadata:
    name: latency-writer-6097-0
spec:
  containers:
    - name: latency-writer-6097-0
      image: 018573873269.dkr.ecr.us-east-1.amazonaws.com/gstreamer:pravega-prod-latency
      imagePullPolicy: Always
      env:
        - name: ENTRYPOINT
          value: "/usr/src/gstreamer-pravega/python_apps/pravega_latency_writer.py --pravega-controller-uri pravega-pravega-controller:9090 --scope benchmark6097 --stream latency --pravega-buffer-size 1024 --video-height 1280 --video-width 720 --video-fps 30 --video-bitrate 5000 --sleep-seconds 0.0"
