{
 "title": "Auto-Scaling",
 "time": { "from": "2025-10-06T12:13:03.389Z", "to": "2025-10-06T12:24:23.686Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Segment Store Instances + Workload Pods",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{condition=\"true\", pod=~\".*pravega-segment-store.*\"}) \r\nor vector(0)",
     "legendFormat": "Segment Store Instances"
    },
    {
     "expr": "(count(kube_pod_status_ready{condition=\"true\", pod=~\".*latency-writer.*\"}) + count(kube_pod_status_ready{condition=\"true\", pod=~\".*latency-reader.*\"})) / 2\r\nor vector(0)",
     "legendFormat": "Workload Instances"
    }
   ]
  },
  {
   "title": "Pravega Segment Stores Instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{condition=\"true\", pod=~\".*pravega-segment-store.*\"}) \r\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workload -Writer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{condition=\"true\", pod=~\".*latency-writer.*\"}) \r\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workload - Reader",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{condition=\"true\", pod=~\".*latency-reader.*\"}) \r\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}