apiVersion: v1
kind: Pod
metadata:
    name: latency-reader-2999-0
spec:
  containers:
    - name: latency-reader-2999-0
      image: 018573873269.dkr.ecr.us-east-1.amazonaws.com/gstreamer:pravega-prod-latency
      imagePullPolicy: Always
      env:
        - name: ENTRYPOINT
          value: "/usr/src/gstreamer-pravega/python_apps/pravega_latency_reader.py --pravega-controller-uri pravega-pravega-controller:9090 --scope benchmark2999 --stream latency --sleep-seconds 5.0"
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
